version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my_database          
      MYSQL_USER: user                     
      MYSQL_PASSWORD: 123456    
    ports:
      - "3306:3306"                        
    # volumes:
    #   - ./mysql_data:/var/lib/mysql
