version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: my_database          
      MYSQL_USER: user                     
      MYSQL_PASSWORD: 123456    
    ports:
      - "3306:3306"                        
    volumes:
      - ./example.sql:/docker-entrypoint-initdb.d/example.sql
      # - ./mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=my_mongodb
    # volumes:
    #   - mongo_data:/data/db 
